# Generated by Django 3.2.18 on 2023-04-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tage',
            new_name='tags',
        ),
    ]
